version: "3"
services:
    mercury_api:
        image: local/mercury-api:latest
        ports:
            - '9005:9005'
        environment:
            MERCURY_REPO_DIR: mercury-api
            MERCURY_LOG_LEVEL: DEBUG
            API_INVENTORY_INVENTORY_ROUTER: tcp://172.16.200.1:9000
            API_RPC_RPC_ROUTER: tcp://172.16.200.1:9001
        volumes:
            - .:/home/mercury
        networks:
            - mercury_internal
            - mercury_public
networks:
    mercury_internal:
        external:
            name: mercury_mercury_internal
    mercury_public:
        external:
            name: mercury_mercury_public




